{% extends "recognition/camera/base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="card shadow">
        <div class="card-body">
            <h5 class="card-title text-center">Заполните данные</h5>
            <form>
                <div class="form-row d-flex">
                    <div class="form-group col-md-6 mt-2">
                        <label for="inputHost">Хост (IP) камеры</label>
                        <input type="text" class="form-control" id="inputHost" placeholder="192.168.0.1" required>
                    </div>
                    <div class="form-group col-md-6 mt-2">
                        <label for="inputPort">Порт</label>
                        <input type="text" class="form-control" id="inputPort" placeholder="554">
                    </div>
                </div>
                <div class="form-group mt-2">
                    <label for="inputRtspPath">Путь до потока RTSP без указания порта и хоста</label>
                    <input type="text" class="form-control" id="inputRtspPath" placeholder="\live\av0">
                </div>
                <div class="form-group mt-2">
                    <label for="inputName">Имя</label>
                    <input type="text" class="form-control" id="inputName" placeholder="Центральный вход" required>
                </div>
                <div class="form-row mt-2">
                    <div class="form-group col-md-4">
                        <label for="inputAuthOption">Вариант авторизации</label>
                        <select id="inputAuthOption" class="form-control">
                            {% for name in camera_names %}
                                <option value="{{ name.id }}" selected>{{ name.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="text-center mt-3">
                    <button id="submitbutton" type="button" class="btn btn-primary">Подключить</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block additional_scripts %}
    <script>
        $(document).ready(function() {
            $('#submitbutton').click(function (event) {  // Используем правильный ID для кнопки

                event.preventDefault();

                const formData = {
                    ip_address: $('#inputHost').val(),
                    port: $('#inputPort').val(),
                    rtsp_path: $('#inputRtspPath').val(),
                    name: $('#inputName').val(),
                    auth: $('#inputAuthOption').val(),
                };

                // Отправляем AJAX-запрос
                $.ajax({
                    url: '{% url 'camera-add-list' %}',
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(formData),
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}'
                    },
                    success: function (response) {
                        console.log('Успех:', response);
                    },
                    error: function (xhr, status, error) {
                        console.error('Ошибка:', status, error);
                    }
                });
            });
        });
    </script>
{% endblock %}
 On branch django
 Changes to be committed:
	modified:   camera_service/__pycache__/camera.cpython-39.pyc
	modified:   src/api_v0/validators.py
	renamed:    src/recognition/templates/recognition/base.html -> src/recognition/templates/recognition/camera/base.html
	renamed:    src/recognition/templates/recognition/camera_auth_detail.html -> src/recognition/templates/recognition/camera/camera_auth_detail.html
	renamed:    src/recognition/templates/recognition/camera_auth_list.html -> src/recognition/templates/recognition/camera/camera_auth_list.html
	new file:   src/recognition/templates/recognition/camera/camera_create.html
	renamed:    src/recognition/templates/recognition/camera_detail.html -> src/recognition/templates/recognition/camera/camera_detail.html
	renamed:    src/recognition/templates/recognition/camera_list.html -> src/recognition/templates/recognition/camera/camera_list.html
	new file:   src/recognition/templates/recognition/camera/index.html
	deleted:    src/recognition/templates/recognition/index.html
	modified:   src/recognition/urls.py
	modified:   src/recognition/views.py
	deleted:    src/staticfiles/css/base_style.css